name: Test
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: golangci/golangci-lint:v1.33-alpine
      env:
        GO111MODULE: "on"
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: |
          golangci-lint run -v && \
          go get -u github.com/mgechev/revive@v1.0.2 && \
          revive -config .revive.toml -formatter friendly ./...
